# Generated by Django 5.2.4 on 2025-08-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], max_length=10)),
                ('plataforma', models.CharField(blank=True, choices=[('prime', 'Amazon Prime'), ('disney', 'Disney+'), ('hbo', 'HBO Max'), ('netflix', 'Netflix'), ('star', 'Star+'), ('vix', 'Vix'), ('otro', 'Otra')], max_length=20)),
                ('calificacion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('meh', 'Regular'), ('mala', 'Mala'), ('horrible', 'Horrible')], max_length=10, null=True)),
                ('veces_vista', models.IntegerField(default=0)),
                ('volveria_a_ver', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('vista', 'Vista'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('tendra_continuacion', models.BooleanField(default=False)),
                ('favorita', models.BooleanField(default=False)),
            ],
        ),
    ]
