# Generated by Django 5.0.6 on 2026-03-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], max_length=10)),
                ('plataforma', models.CharField(blank=True, choices=[('prime', 'Amazon Prime'), ('disney', 'Disney+'), ('hbo', 'HBO Max'), ('netflix', 'Netflix'), ('star', 'Star+'), ('vix', 'Vix'), ('otro', 'Otra')], max_length=20)),
                ('calificacion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('horrible', 'Horrible')], max_length=10, null=True)),
                ('veces_vista', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('vista', 'Vista'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('volveria_a_ver', models.BooleanField(default=False)),
                ('tendra_continuacion', models.BooleanField(default=False)),
                ('favorita', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase_kanban', models.CharField(choices=[('nuevo', 'Nuevo'), ('pronto', 'Pronto'), ('encurso', 'En curso'), ('pausado', 'Pausado')], db_index=True, default='nuevo', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SagaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Maraton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenidos', models.ManyToManyField(blank=True, related_name='maratones', to='cinetrack.contenido')),
            ],
        ),
    ]
