# Generated by Django 5.2.4 on 2025-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0002_contenido_created_at_contenido_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='fase_kanban',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('pronto', 'Pronto'), ('encurso', 'En curso'), ('pausado', 'Pausado')], db_index=True, default='nuevo', max_length=12),
        ),
    ]
