# Generated by Django 5.2.4 on 2025-09-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0003_contenido_fase_kanban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='calificacion',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala'), ('horrible', 'Horrible')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
