# Generated by Django 5.2.4 on 2025-09-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0004_alter_contenido_calificacion_alter_contenido_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SagaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
