# Generated by Django 5.2.4 on 2025-09-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0005_sagaalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maraton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenidos', models.ManyToManyField(blank=True, related_name='maratones', to='cinetrack.contenido')),
            ],
        ),
    ]
