# Generated by Django 5.2.4 on 2026-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0006_maraton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='veces_vista',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
