# Generated by Django 5.2.4 on 2026-07-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0008_migrate_star_to_disney'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='maraton',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='sagaalias',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='contenido',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('prime', 'Amazon Prime'), ('disney', 'Disney+'), ('hbo', 'HBO'), ('netflix', 'Netflix'), ('vix', 'Vix'), ('otro', 'Otra')], max_length=20),
        ),
    ]
