# Generated by Django 5.2.4 on 2025-07-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeriePelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=10)),
                ('plataforma', models.CharField(max_length=100)),
                ('calificacion', models.IntegerField()),
                ('veces_vista', models.IntegerField(default=1)),
                ('volveria_a_ver', models.BooleanField(default=False)),
            ],
        ),
    ]
