# Generated by Django 5.2.4 on 2025-07-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriepelicula',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='tipo',
            field=models.CharField(choices=[('serie', 'Serie'), ('pelicula', 'Película')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='veces_vista',
            field=models.IntegerField(default=0),
        ),
    ]
