# Generated by Django 5.2.4 on 2025-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_seriepelicula_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriepelicula',
            name='tipo',
            field=models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], max_length=10),
        ),
    ]
