# Generated by Django 5.2.4 on 2025-07-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_seriepelicula_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriepelicula',
            name='plataforma',
            field=models.CharField(choices=[('Netflix', 'Netflix'), ('Amazon Prime Video', 'Amazon Prime Video'), ('HBO', 'HBO'), ('Disney+', 'Disney+'), ('Star+', 'Star+'), ('Vix', 'Vix')], max_length=50),
        ),
    ]
