# Generated by Django 5.2.4 on 2025-07-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_seriepelicula_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriepelicula',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seriepelicula',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='seriepelicula',
            name='resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('prime', 'Amazon Prime'), ('disney', 'Disney+'), ('hbo', 'HBO Max'), ('star', 'Star+'), ('otro', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
