# Generated by Django 5.2.4 on 2025-07-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_seriepelicula_fecha_seriepelicula_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriepelicula',
            name='estado',
            field=models.CharField(choices=[('vista', 'Vista'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
    ]
