# Generated by Django 5.2.4 on 2025-07-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_seriepelicula_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriepelicula',
            name='favorita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seriepelicula',
            name='tendra_continuacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seriepelicula',
            name='calificacion',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('meh', 'Regular'), ('mala', 'Mala'), ('horrible', 'Horrible')], max_length=10, null=True),
        ),
    ]
