# Generated by Django 5.2.4 on 2025-07-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_seriepelicula_favorita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriepelicula',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('netflix', 'Netflix'), ('prime', 'Amazon Prime'), ('disney', 'Disney+'), ('hbo', 'HBO Max'), ('star', 'Star+'), ('vix', 'Vix'), ('otro', 'Otra')], max_length=20),
        ),
    ]
