# Generated by Django 5.2.4 on 2025-07-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_seriepelicula_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriepelicula',
            name='plataforma',
            field=models.CharField(blank=True, choices=[('prime', 'Amazon Prime'), ('disney', 'Disney+'), ('hbo', 'HBO Max'), ('netflix', 'Netflix'), ('star', 'Star+'), ('vix', 'Vix'), ('otro', 'Otra')], max_length=20),
        ),
    ]
